# Generated by Django 4.0.6 on 2022-07-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=75)),
                ('ptero_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('server_id_hex', models.CharField(max_length=10)),
                ('creation_date', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BillDash.customer')),
            ],
        ),
    ]
