# Generated by Django 4.0.6 on 2022-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillDash', '0002_customer_user_server_plan_alter_server_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_id',
            new_name='Admin Server ID',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_id_hex',
            new_name='Server ID',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
