# Generated by Django 4.0.6 on 2022-08-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillDash', '0003_rename_server_id_server_admin server id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
