# Generated by Django 4.0.6 on 2022-08-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillDash', '0004_remove_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=25)),
                ('network_allocations', models.IntegerField(default=1)),
                ('backups', models.IntegerField(default=0)),
                ('databases', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BillDash.customer')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='last_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BillDash.payment'),
        ),
        migrations.AlterField(
            model_name='server',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BillDash.plan'),
        ),
    ]
