# Generated by Django 4.0.6 on 2022-08-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillDash', '0008_bill_remove_server_last_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
