# Generated by Django 4.0.6 on 2022-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillDash', '0009_remove_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
